### ISSUE TITLE
Font-Awesome Access

### ISSUE THREAD

**Issue by Azurewren** [madodig/wikijs-customization#1]
I am trying to use the Font Awesome 5 icons for the Collapsible menu suffix. Is it possible, if so, how should it be implemented?

**Comment by madodig** [comment]
Hi! Thanks for bringing this up. I've been using only Material Design icon set, so I haven't implemented the Font Awesome icon set support.
I've fixed it now. To use Font Awesome icon set, just use it as you would use it natively in Wiki.js, so the suffix in the collapsible menu items should be, for example:
for Font Awesome 5:
`#fas fa-home#`
for Font Awesome 4:
`#fa fa-home#`.
