### ISSUE TITLE
upstream pull request

### ISSUE THREAD

**Issue by Sylensky** [madodig/wikijs-customization#10]
Hi,

is there any specific reason why this wholesome and (IMO essential wiki feature) is not being upstreamed?
Aside from it being a obvious hack.

**Comment by madodig** [comment]
Hi,

this is custom JS/CSS code to be injected in the Wiki.js, this does not modify the Wiki.js source code so it can't be synced with the upstream repo.
Wiki.js team is working on version 3, I think I saw some of the features implemented there. I'm not sure about the collapsible menu, although I've seen it as planned (3rd most requested feature) on https://requarks.canny.io/wiki. You can upvote it or suggest other features there.

Thanks for the feedback btw, I'm glad you find this useful.
