### ISSUE TITLE
Which one to use or download or folder to use 

### ISSUE THREAD

**Issue by lalrochhara** [madodig/wikijs-customization#11]
Hello sir/ma'am , i clone requark repo from GitHub, but I don't know which folder to use as wikijs main scripts, also i downloaded from their wiki paage, but i don't see any folder you mentioned and others important folder like others and here in your document mentioned, so where can i found the right script to use complete wikijs?

I'm just begginer and also search everything i can, I don't see any of this, can you explain or mention only wikijs without their non important file and folder from them? Please.

Thanks in advance.

**Comment by madodig** [comment]
Hi, you can download `mad-wikijs-customization.css` and `mad-wikijs-customization.js` files an upload them to your wiki instance. 

Then navigate to Wiki.js Administration / Theme and reference those files in `Body HTML Injection` field. Example:
```
<link rel="stylesheet" href="/public/code/mad-wikijs-customization.css">
<script src="/public/code/mad-wikijs-customization.js"></script>
```
Note that I've used `/public/code` folder here, you can choose any folder you use for public content (users must be allowed to access those files).

Paste the contents of `wjs_html-injection-code.head` file to the `Head HTML Injection` field and modify the values if needed.
