### ISSUE TITLE
Uncaught ReferenceError: slidingMenu is not defined at mad-wikijs-customization.js:1

### ISSUE THREAD

**Issue by kpurikhova** [madodig/wikijs-customization#5]
Import fails

**Comment by madodig** [comment]
Can you provide more details?
How did you import the code (which option from readme)?
It looks like variables are not defined, so when the code is run it can not reference them. What are the contents of Head HTML Injection field under Administration / Theme?

**Comment by kpurikhova** [comment]
Sorry, my bad. I didn't paste all variables from wjs_html-injection-code.head. Now it's working
