### ISSUE TITLE
install confusion.

### ISSUE THREAD

**Issue by mindcloud69** [madodig/wikijs-customization#7]
Look at the simple install locally hosted code. where exactly do you put the files you are referencing.  
like
```
<style>
    code/mad-wikijs-customization.css contents
</style>
```
where is the mad-wikijs-customization.css file stored?

**Comment by madodig** [comment]
As stated in the readme: "**Wrap the contents** of code/mad-wikijs-customization.css file with HTML <style> tag **and paste** it in the CSS Override field".
In github, navigate to `code/mad-wikijs-customization.css` file, copy its contents ("Copy raw contents" button), navigate to your Wiki Administration/Theme, paste the contents inside CSS Override field, and then type "<style>" to the beginning, and "</style>" to the end:

The contents of the `CSS Override` field should then look something like this:
```
<style>
    /* https://github.com/madodig/wikijs-customization */
.contents summary{border:0.....
</style>
```

Do the same for the `Head HTML Injection` and apply the changes.
